spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.162/wx_pay?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
wechat:
  #公众账号,授权
  #wx915d7b09631af813
  mpAppid: wxd898fcb01713c658
  #mpAppid: wx915d7b09631af813
  mpAppSecret: d31e0dd82028d434de3b9f4c7c83b90c
  #支付/商户号
  mchID: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  #发起支付不需要证书  退款需要
  keyPath: F:\wx_pay\coding-117\doc\h5.p12
  notifyUrl: http://xiaohat.natapp1.cc/sell/pay/notify